settings:
  lobbyVersion: true
  maxHealth: 60
  maxhomes: 1
  teleportWaitTime: 5
  autoBroadcastDelay: 60
  removeOnQuit: false
  database:
    hostname: '127.0.0.1'
    port: 3306
    database: subbo_trilar
    username: subbo_trilar
    password: 2lyY39Jt
  broadcastMessages:
    - '&6Welcome to &eTrilar&6!'
    - '&6Do you have any questions? Feel free to ask!'
    - '&6See a bug? Visit the forum and tell us!'