settings:
  maxHealth: 60
  maxhomes: 1
  teleportWaitTime: 5
  autoBroadcastDelay: 60
  removeOnQuit: false
  database:
    hostname: '185.211.51.30'
    port: 3306
    database: core
    username: root
    password: Pedo1234
  broadcastMessages:
    - '&6Welcome to &eTrilar&6!'
    - '&6Do you have any questions? Feel free to ask!'
    - '&6See a bug? Visit the forum and tell us!'