settings:
  lobbyVersion: true
  maxHealth: 60
  maxhomes: 1
  teleportWaitTime: 5
  autoBroadcastDelay: 60
  enableAutoBroadcast: false
  removeOnQuit: false
  database:
    hostname: phpmyadmin.danibaas.nl
    port: 3306
    database: trilar
    username: trilar
    password: pgr6WdgRXhnhwJNm
  broadcastMessages:
    - '&6Welcome to &eTrilar&6!'
    - '&6Do you have any questions? Feel free to ask!'
    - '&6See a bug? Visit the forum and tell us!'