name: Trilar_Core
main: me.shizleshizle.core.Main
version: 0.0.1
api-version: 1.13
authors: [shizleshizle, iMelvin]
commands:
#ban
  ban:
    description: Ban a player
  unban:
    description: Unban a player
    aliases: [pardon]
  kick:
    description: Kick a player
  mute:
    description: Mute a player
  unmute:
    description: Unmute a player
#clearlag
  unloadchunks:
    description: Unload unused chunks
  clearentities:
    description: Clear entites on the ground
#home
  delhome:
    description: Delete a home.
  home:
    description: Teleport to your home.
  sethome:
    description: Set a home.
#messages
  msg:
    description: Message a person
    aliases: [message, mssg]
  reply:
    description: Reply to a person
    aliases: [r]
  socialspy:
    description: Spy on people messaging
#spawn
  spawn:
    description: Go to spawn.
  setspawn:
    description: set spawn.
  removespawn:
    description: remove spawn.
#teleportation
  tp:
    description: Teleport yourself or others.
    aliases: [teleport]
  tpa:
    description: Send a teleport request to a player.
  tpaccept:
    description: Accept a teleport request from a player.
    aliases: [tpyes, tpconfirm, tpja]
  tpahere:
    description: Send a request to make a player teleport to you.
  tpall:
    description: Teleport all players to you.
  tpdeny:
    description: Deny a teleport request from a player.
    aliases: [tpno, tpcancel, tpnee]
  tphere:
    description: Teleport a player to you.
  tpo:
    description: Override a players TpToggle and teleport to him/her.
  tpohere:
    description: Override a players TpToggle and teleport him/her to you.
  tppos:
    description: Teleport to a certain location.
  tptoggle:
    description: Toggle teleportation to you.
#tickets
  checkticket:
    description: Look up a ticket and its info.
  closeticket:
    description: Close or reopen a ticket.
  taketicket:
    description: Teleport to a ticket.
  ticket: 
    description: Create a ticket.
  tickets:
    description: View all (your) tickets.  
#time
  time:
    description: Change the timeline like the Flash.
  day:
    description: Change the time to day because you dont like night.
  night:
    description: Change the time to night because you dont like day.
  ptime:
    description: Change your personal time.
    aliases: [playertime]
#vault
  playervaults:
    description: Open or create a personal vault
    aliases: [playervault, pv, playerv, pvault]
  #econ
  balance:
    description: Check your balance.
  pay:
    description: Pay someone money.
#warps
  removewarp:
    description: Remove a Warp.
    aliases: [deletewarp, delwarp, dwarp]
  setwarp:
    description: Set a Warp to your Location.
    aliases: [swarp]
  warp:
    description: Teleport to a Warp.
#weather
  weather:
    description: Change the weather.
  sun:
    description: Change it to sun.
    aliases: [clear]
  storm:
    description: Change it to storm.
    aliases: [rain, downfall]
#gewone commands
  autobroadcaster:
    description: Toggle Auto-Broadcaster
    aliases: [ab, autob, autobroadcast]
  afk:
    description: Toggle AFK.
  back:
    description: Go to your previous location.
  broadcast:
    description: Send a message to everyone on the server.
    aliases: [bc]
  chatcolor:
    description: Change your ChatColor.
    aliases: [chatc]
  clearchat:
    description: Clear the chat.
    aliases: [clearc]
  clearinventory:
    description: Clear an inventory.
    aliases: [clear, ci]
  commandspy:
    description: See all commandspy commands.
    aliases: [cspy]
  enchant:
    description: Enchant an item
  enderchest:
    description: Open an enderchest
    aliases: [echest, ec]
  feed:
    description: Feed yourself or others.
  fly:
    description: Toggle fly.
  freeze:
    description: Freeze a player.
  gamemode:
    description: Change your gamemode.
    aliases: [gm]
  gms:
    description: Change your gamemode.
  gmc:
    description: Change your gamemode.
  gmsp:
    description: Change your gamemode.
  gma:
    description: Change your gamemode.
  getpos:
    description: Get a players position.
  god:
    description: Toggle god mode.
  hat:
    description: Set an item as your hat.
  heal:
    description: Heal yourself or others.
  help:
    description: Get some info.
  invsee:
    description: Open someone inventory.
  item:
    description: Give yourself or someone an item
    aliases: [give, giveitem]
  kill:
    description: Kill a player.
  killmobs:
    description: Kill mobs within specified radius
  list:
    description: List all online player(s).
  maintenance:
    description: Toggle lockdown mode.
  mccore:
    description: Reload the plugin
  me:
    description: Talk in third person.
  mods:
    description: View the allowed mods.
  motd:
    description: Set or view the message of the day
  name:
    description: Set an item name or description
  nickname:
    description: Change your nickname.
    aliases: [nick]
  permission:
    description: View or change peoples permission(s).
  prefix:
    description: View or change peoples prefix.
  rank:
    description: Change a persons rank.
  repair:
    description: Repair one or more items.
    aliases: [fix]
  rules:
    description: View the rules.
  skull:
    description: Get yourself a skull.
  smelt:
    description: Smelt ores into ingots
  socialmedia:
    description: View our socialmedia!
  spawnmob:
    description: Spawn a specific mob
  speed:
    description: Change your fly or walk speed.
  staffchat:
    description: Talk among your self staff members
    aliases: [sc, staffc, schat]
  staff:
    description: View online staff.
    aliases: [stafflist, sl]
  suicide:
    description: Kill yourself.
  vanish:
    description: View/hide yourself.
    aliases: [v]
  whois:
    description: View a player and they settings
  wild:
    description: Teleport somewhere random.
  workbench:
    description: Open a workbench.
    aliases: [wb]